CREATE DATABASE IF NOT EXISTS ecommerce_interview;

USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);


CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- PART 1: Customer & Inventory Filtering
-- Business Requirement: The marketing and inventory teams want to identify customer acquisition trends and inventory risks.
-- Q1. Show all customers from Bengaluru.
select * from customers where city="Bengaluru";

-- Q2. Show customers who signed up after ‘2025-01-01’.
select * from customers where signup_date>'2025-01-01';

-- Q3. Find customers from Mumbai and Hyderabad.
select * from customers where city="Mumbai" or city="Hyderabad";

-- Q4. Show products belonging to the Electronics category.
select * from products;
select * from products where category="Electronics";

-- Q5. Find products priced above 40000.
select * from products where price>40000;

-- Q6. Show products where stock is less than 20.
select * from products where stock<20;

-- Q7. Find products with stock between 50 and 100.
select * from products where stock between 50 and 100;

-- Q8. Show customers whose names start with ‘A’.
select * from customers;
select * from customers where customer_name like 'A%';

-- Q9. Find products whose names contain ‘Premium’.
select * from products;
select * from products where product_name like '%Premium%';

-- Q10. Show customers registered during the year 2025.
select * from customers where year(signup_date)=2025;


-- PART 2: Revenue & Sales Analysis
-- Business Requirement: The finance department wants summarized revenue and sales insights.
-- Q11. Find total revenue generated by each category.
select * from products;
select category,sum(price) from products group by category;

-- Q12. Find total quantity sold for each product.
select * from order_items;
select * from products;
select product_id,sum(quantity) from order_items group by product_id;

-- Q13. Find total orders under each order status.
select * from orders;
select count(order_id) as total_orders,status from orders group by status;

-- Q14. Find total revenue generated through each payment method.
select * from orders;
select o.payment_method ,sum(oi.quantity*oi.unit_price) as total_revenue
from orders o
join order_items oi
on o.order_id=oi.order_id
group by o.payment_method;

-- Q15. Find average product price category-wise.
select category,avg(price) as Average_product_price from products group by category;

-- Q16. Find category-wise quantity sold.
select p.category,sum(oi.quantity)
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.category;

-- Q17. Find monthly order count.
select date_format(order_date,'%M') as month,count(order_id) as orders from orders group by month;

-- Q18. Find monthly revenue trend.
select date_format(o.order_date,'%M') as month,sum(oi.quantity*oi.unit_price) as revenue 
from orders o
join order_items oi
on o.order_id=oi.order_id
group by month;

-- Q19. Find the most commonly used payment method.
select payment_method as common_payment_method, count(payment_method) as total_count
from orders 
group by common_payment_method 
order by total_count desc 
limit 1;

-- Q20. Find the highest revenue-generating category.
select p.category,sum(oi.quantity*oi.unit_price) as Revenue 
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.category
order by Revenue desc
limit 1;


-- PART 3: High-Value Business Insights
-- Business Requirement: Management wants to identify high-performing customers, products, and regions.
-- Q21. Find customers who placed more than 5 orders.
select * from orders;
select c.customer_id,c.customer_name,count(o.order_id) as no_of_orders
from customers c
join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
having count(o.order_id)>5;

-- Q22. Find top 5 customers based on total spending.
select c.customer_id,c.customer_name,sum(oi.quantity*oi.unit_price) as total_spending
from customers c
join orders o
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_id,c.customer_name
order by total_spending desc
limit 5;

-- Q23. Find products sold more than 30 times.
select p.product_id,p.product_name,sum(oi.quantity)  as No_of_products_sold
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_id,p.product_name
having No_of_products_sold>30;

-- Q24. Find categories generating revenue greater than 500000.
select p.category,sum(oi.quantity*oi.unit_price) as total_revenue
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.category
having total_revenue>500000;

-- Q25. Find cities having more than 10 customers.
select city,count(customer_id) as no_of_customers from customers group by city having no_of_customers>10;

-- Q26. Find the top 5 highest-selling products.
select p.product_id,p.product_name,sum(oi.quantity) as no_of_products_sold 
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_id,p.product_name
order by no_of_products_sold desc
limit 5;

-- Q27. Find the top 3 most profitable products.
select p.product_id,p.product_name,sum(oi.quantity*oi.unit_price) as total_revenue
from products p 
join order_items oi
on p.product_id=oi.product_id
group by p.product_id,p.product_name
order by total_revenue desc
limit 3;

-- Q28. Find customers whose spending is above average customer spending.
select c.customer_id,c.customer_name,sum(oi.quantity*oi.unit_price) as total_spending
from customers c 
join orders o 
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_id,c.customer_name
having sum(oi.quantity*oi.unit_price) > 
(
select avg(customer_spending)
from (
select sum(oi.quantity* oi.unit_price) as customer_spending
from orders o
join order_items oi
on o.order_id=oi.order_id
group by o.customer_id) as average_spending
);

-- Q29. Find products contributing more than 10% of company revenue.
select p.product_id,p.product_name,sum(oi.quantity*oi.unit_price) as total_revenue
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_id,p.product_name
having total_revenue >
( select sum(quantity*unit_price)*0.10 from order_items);

-- Q30. Find the city generating the highest revenue.
select c.city,sum(oi.quantity*oi.unit_price) as total_revenue
from customers c
join orders o
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.city
order by total_revenue desc
limit 1;


-- PART 4: Customer & Product Intelligence
-- Business Requirement: The CRM and product teams want detailed operational insights.

-- Q31. Display all orders along with customer names.
-- Normal Query
select o.*,c.customer_name
from orders o
join customers c
on o.customer_id=c.customer_id;

-- CTE
With customer_info as(
select o.*,c.customer_name
from orders o
join customers c
on o.customer_id=c.customer_id)
select * from customer_info;

-- Q32. Find total revenue generated by each customer.
select c.customer_id,c.customer_name,sum(oi.quantity*oi.unit_price) as total_revenue
from customers c 
join orders o
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_id,c.customer_name;

-- Q33. Find total number of orders placed by each customer.
select c.customer_id,c.customer_name,count(o.order_id) as total_orders
from customers c
join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name;

-- Q34. Find customers who never placed any orders.
select c.customer_id,c.customer_name
from customers c
left join orders o 
on c.customer_id=o.customer_id
where o.order_id is null;

-- Q35. Find the latest order date for each customer.
select c.customer_id,c.customer_name,max(o.order_date) as latest_order_date 
from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name;

-- Q36. Find product-wise revenue generated.
select p.product_id,p.product_name,sum(oi.quantity*oi.unit_price) as total_revenue
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_id,p.product_name;

-- Q37. Find products that were never sold.
select p.product_id,p.product_name from products p
left join order_items oi
on p.product_id=oi.product_id
where oi.product_id is null; 

-- Q38. Find products whose stock is lower than total quantity sold.
select p.product_name,p.stock,sum(oi.quantity) as total_quantity_sold
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_name,p.stock
having p.stock < total_quantity_sold;

-- Q39. Find category-wise revenue contribution percentage.
select p.category,sum(oi.quantity*oi.unit_price) as category_revenue,
sum(oi.quantity*oi.unit_price)*100/(select sum(quantity*unit_price) from order_items) as revenue_percentage
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.category;

-- Q40. Find repeat customers who ordered in multiple months.
-- Normal Query
select c.customer_name,count(monthname(o.order_date)) as order_month 
from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_name
having order_month > 1
order by order_month desc ;

-- CTE
WITH repeated_customers as(
select c.customer_name,count(monthname(o.order_date)) as order_month 
from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_name
having order_month > 1
order by order_month desc)
select * from repeated_customers ;

-- View
create view repeated_customers1 as
select c.customer_name,count(monthname(o.order_date)) as order_month 
from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_name
having order_month > 1
order by order_month desc;
select * from repeated_customers1;

-- Stored Procedures
DELIMITER $$
create procedure repeated_customers2()
Begin 
select c.customer_name,count(monthname(o.order_date)) as order_month 
from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_name
having order_month > 1
order by order_month desc;
END $$
DELIMITER ; 
call repeated_customers2;
select * from repeated_customers2;


-- PART 5: Executive-Level Analytics
-- Business Requirement: The leadership team wants strategic business KPIs for decision-making.
-- Q41. Calculate overall company revenue.
select sum(quantity*unit_price) as total_company_revenue from order_items;

-- Q42. Calculate average order value.
SELECT sum(oi.quantity * oi.unit_price) / Count(Distinct o.order_id) as average_order_value
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id;

-- Q43. Calculate cancelled order percentage.
select status,count(order_id)*100.0/(select count(*) from orders) as  cancelled_precentage 
from orders where status="Cancelled" group by status;

-- Q44. Find the month with highest revenue.
select date_format(o.order_date,"%m") as month,sum(oi.quantity*oi.unit_price) as revenue
from orders o
join order_items oi 
on o.order_id=oi.order_id
group by month
order by revenue desc;

-- Q45. Find the month with highest order volume.
select date_format(order_date,"%m") as month,count(order_id) as order_volume
from orders 
group by month 
order by order_volume desc
limit 1;

-- Q46. Find the most common order status.
select status,count(status) 
from orders 
group by status
order by status desc
limit 1;

-- Q47. Generate a payment-method-wise revenue report.
select o.payment_method,sum(oi.quantity*oi.unit_price) as revenue
from orders o
join order_items oi
on o.order_id=oi.order_id
group by o.payment_method 
order by revenue desc;

-- Q48. Generate a category-wise business summary report.
Select p.category,count(Distinct oi.order_id) as total_orders,
sum(oi.quantity) as total_quantity_sold,
sum(oi.quantity*oi.unit_price) as total_revenue
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.category
order by total_revenue desc;

-- Q49. Generate a city-wise customer and revenue report.
select c.city,c.customer_id,c.customer_name,sum(oi.quantity*oi.unit_price) as revenue 
from customers c
join orders o 
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.city,c.customer_id,c.customer_name
order by revenue desc;

-- Q50. Generate a final executive sales report containing:
-- ●	Customer Name
-- ●	Product Name
-- ●	Category
-- ●	Quantity
-- ●	Unit Price
-- ●	Revenue
-- ●	Order Date
-- ●	Order Status
-- ●	Payment Method
-- ●	Customer City
select c.customer_name,p.product_name,p.category,oi.quantity,oi.unit_price,oi.quantity*oi.unit_price as revenue,
o.order_date,o.status,o.payment_method,c.city
from customers c
join orders o
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
join products p
on oi.product_id=p.product_id
order by revenue desc;












